language: python
python:
  - "2.7"

env:
  - CFLAGS="-O0"

# before_install:
#   - sudo apt-get install -qq libxml2-dev libxslt-dev postgresql-contrib

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "cd sgk"
  - "python manage.py syncdb --noinput"
  - "python manage.py migrate"
  - "python manage.py test"
